spring:
  application:
    name: trading-platform

  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
      timeout: 2s

kis:
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}
  rest-base-url: https://openapivts.koreainvestment.com:29443
server:
  port: ${SERVER_PORT}
